/**
 * 官方配置初始数据。
 * - 开发/CI:`pnpm config:validate` 直接校验本文件约束
 * - 写入 DB:`pnpm db:seed` 清空 gear_items 后按本文件全量写入
 *
 * 真实装备数据请替换占位条目,并将 enabled 设为 true。
 * 规范见 docs/03-spec/CONFIG-SCHEMA.md / DATA-MODEL.md。
 */

export const OFFICIAL_CONFIG_ID = 'official' as const;

export const OFFICIAL_VERSION_TAG = '2026.07.25';

/**
 * operatorWeight = 0:干员被认为没有强弱区分,不参与综合评分计算(总分贡献恒为 0),
 * 但仍按各干员的 GearItem.weight(抽取权重,与此处评分权重是两个独立字段)正常参与随机抽取。
 * 见 docs/03-spec/CONFIG-SCHEMA.md 2.2 节"评分中立槶位"用法说明。
 */
export const OFFICIAL_WEIGHTS = {
  weaponWeight: 0.55,
  helmetWeight: 0.2,
  armorWeight: 0.25,
  operatorWeight: 0,
} as const;

export type SeedGearCategory = 'weapon' | 'helmet' | 'armor' | 'operator';
export type SeedGearRarity = 'common' | 'rare' | 'epic' | 'legendary';

export interface SeedGearItem {
  id: string;
  category: SeedGearCategory;
  name: string;
  subCategory?: string;
  baseScore: number;
  rarity?: SeedGearRarity;
  weight?: number;
  imageUrl?: string;
  description?: string;
  enabled: boolean;
}

/** 占位数据:正式录入前请替换为真实条目。 */
export const SEED_GEAR_ITEMS: SeedGearItem[] = [
  {
    id: 'weapon_m4a1',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'M4A1突击步枪',
    baseScore: 68,
    imageUrl: '/gear/weapon/weapon_m4a1.png',
    description: 'M4A1突击步枪，使用5.56×45mm口径弹药，火力十分可靠。',
    enabled: true,
  },
  {
    id: 'weapon_akm',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'AKM突击步枪',
    baseScore: 69,
    imageUrl: '/gear/weapon/weapon_akm.png',
    description: '7.62×39mm口径经典全自动突击步枪，拥有强大火力但需要足够的技巧。',
    enabled: true,
  },
  {
    id: 'weapon_qbz95-1',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'QBZ95-1突击步枪',
    baseScore: 60,
    imageUrl: '/gear/weapon/weapon_qbz95-1.png',
    description:
      '使用5.8×42mm子弹的全自动无托式突击步枪，拥有较快射速和舒适操控，改进后拥有空仓挂机功能。',
    enabled: true,
  },
  {
    id: 'weapon_aks-74u',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'AKS-74U突击步枪',
    baseScore: 52,
    imageUrl: '/gear/weapon/weapon_aks-74u.png',
    description: 'AKS-74U突击步枪是1979年开始列装的5.45×39mm短突击步枪，直至现在仍有许多国家使用。',
    enabled: true,
  },
  {
    id: 'weapon_ash-12',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'ASh-12战斗步枪',
    baseScore: 78,
    imageUrl: '/gear/weapon/weapon_ash-12.png',
    description:
      'Ash-12突击步枪是一种大口径无托突击步枪，也是一种近身距离作战及城市作战专用的武器，发射12.7×55mm口径步枪子弹。',
    enabled: true,
  },
  {
    id: 'weapon_k416',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'K416突击步枪',
    baseScore: 77,
    imageUrl: '/gear/weapon/weapon_k416.png',
    description:
      'K416突击步枪是一款德国制造的突击步枪。使用5.56x45mm子弹，具有高度可靠性和优秀的射击性能，广泛应用于全球多个国家的军队和特种部队。',
    enabled: true,
  },
  {
    id: 'weapon_m16a4',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'M16A4突击步枪',
    baseScore: 50,
    imageUrl: '/gear/weapon/weapon_m16a4.png',
    description: '发射5.56×45mm子弹，采用三连发点射模式的步枪，具备较高的精确度。',
    enabled: true,
  },
  {
    id: 'weapon_aug',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'AUG突击步枪',
    baseScore: 68,
    imageUrl: '/gear/weapon/weapon_aug.png',
    description: '使用5.56×45mm子弹的精确稳定无托突击步枪，适合在中远距离使用。',
    enabled: true,
  },
  {
    id: 'weapon_m7',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'M7战斗步枪',
    baseScore: 93,
    imageUrl: '/gear/weapon/weapon_m7.png',
    description: 'M7是一款新式步枪，使用6.8×51mm全威力弹药。',
    enabled: true,
  },
  {
    id: 'weapon_sg552',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'SG552突击步枪',
    baseScore: 57,
    imageUrl: '/gear/weapon/weapon_sg552.png',
    description: 'SG552突击步枪使用5.56×45mm口径弹药，枪机设计与AK类似。',
    enabled: true,
  },
  {
    id: 'weapon_ak12',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'AK-12突击步枪',
    baseScore: 60,
    imageUrl: '/gear/weapon/weapon_ak12.png',
    description:
      'AK12是一款由俄罗斯生产的5.45×39mm口径突击步枪，采用模块化设计，具有高精度和可靠性，可适应不同的战斗环境和需求，是俄罗斯军队的主要装备之一。',
    enabled: true,
  },
  {
    id: 'weapon_scar-h',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'SCAR-H战斗步枪',
    baseScore: 70,
    imageUrl: '/gear/weapon/weapon_scar-h.png',
    description:
      'SCAR-H是一款由比利时生产的7.62×51mm口径战斗步枪，具有高精度和可靠性，采用模块化设计，可根据需求进行改装，被广泛应用于军警部队。',
    enabled: true,
  },
  {
    id: 'weapon_g3',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'G3战斗步枪',
    baseScore: 60,
    imageUrl: '/gear/weapon/weapon_g3.png',
    description: '使用7.62×51mm子弹的经典、可靠全威力弹战斗步枪。',
    enabled: true,
  },
  {
    id: 'weapon_ptr-32',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'PTR-32突击步枪',
    baseScore: 62,
    imageUrl: '/gear/weapon/weapon_ptr-32.png',
    description:
      'PTR-32是基于G3步枪改进而来，发射7.62×39mm中间威力步枪弹的突击步枪，通用AKM弹匣，火力强大。',
    enabled: true,
  },
  {
    id: 'weapon_car-15',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'CAR-15突击步枪',
    baseScore: 50,
    imageUrl: '/gear/weapon/weapon_car-15.png',
    description:
      'CAR-15步枪是缩短卡宾型AR步枪的通用名称，采用5.56×45mm口径弹药，此特定型号为723型。',
    enabled: true,
  },
  {
    id: 'weapon_asval',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'AS Val突击步枪',
    baseScore: 90,
    imageUrl: '/gear/weapon/weapon_asval.png',
    description: '发射9×39mm特种弹药的俄式微声突击步枪，穿透性能强大。',
    enabled: true,
  },
  {
    id: 'weapon_tenglong',
    category: 'weapon',
    subCategory: 'rifle',
    name: '腾龙突击步枪',
    baseScore: 85,
    imageUrl: '/gear/weapon/weapon_tenglong.png',
    description:
      '采用新思路、新技术、新结构、新材料、新工艺的新式国产突击步枪，使用5.8×42mm口径弹药，模块化设计可以适应多种环境和任务需求。',
    enabled: true,
  },
  {
    id: 'weapon_k437',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'K437突击步枪',
    baseScore: 79,
    imageUrl: '/gear/weapon/weapon_k437.png',
    description:
      'K437是一款德国的模块化突击步枪，发射.300BLK弹药。其侧折叠枪托便于隐蔽携带，短行程导气系统确保了高可靠性',
    enabled: true,
  },
  {
    id: 'weapon_kc17',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'KC17突击步枪',
    baseScore: 80,
    imageUrl: '/gear/weapon/weapon_kc17.png',
    description:
      'KC-17是俄罗斯研发的一款紧凑型突击步枪，枪身采用高强度聚合物材料，减轻了重量并提升了人机功效，有望成为俄制轻武器的新星。',
    enabled: true,
  },
  {
    id: 'weapon_mk47',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'MK47突击步枪',
    baseScore: 95,
    imageUrl: '/gear/weapon/weapon_mk47.png',
    description:
      'MK47是由美国设计生产的一款突击步枪通过深度优化AR-15平台以适配7.62x39mm弹药，并实现了枪托可折叠，是融合创新工艺和凶猛火力的典范',
    enabled: true,
  },
  {
    id: 'weapon_mcxlt',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'MCX LT突击步枪',
    baseScore: 71,
    imageUrl: '/gear/weapon/weapon_mcxlt.png',
    description:
      'MCX LT是美国设计生产的一款突击步枪，可以很好地适配消音器，是一款优秀的近战暗杀武器.',
    enabled: true,
  },
  {
    id: 'weapon_ar57',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'AR57突击步枪',
    baseScore: 68,
    imageUrl: '/gear/weapon/weapon_ar57.png',
    description:
      'AR57沿用了AR15下机匣，重新改造后的枪支将原本抛壳口替换到弹匣装填口，避免高射速下弹壳抛出影响瞄准',
    enabled: true,
  },
  {
    id: 'weapon_rm277',
    category: 'weapon',
    subCategory: 'rifle',
    name: 'RM277突击步枪',
    baseScore: 68,
    imageUrl: '/gear/weapon/weapon_rm277.png',
    description:
      '为击穿下一代防弹插板而生的6.8mm无托步枪，紧凑的机身与暴烈的膛压让它在中距离对抗中拥有压倒性的终点效能',
    enabled: true,
  },
  {
    id: 'weapon_mp5',
    category: 'weapon',
    subCategory: 'SMG',
    name: 'MP5冲锋枪',
    baseScore: 48,
    imageUrl: '/gear/weapon/weapon_mp5.png',
    description: '采用9×19mm弹药的全自动冲锋枪，在各项性能上都达到完美平衡。',
    enabled: true,
  },
  {
    id: 'weapon_p90',
    category: 'weapon',
    subCategory: 'SMG',
    name: 'P90冲锋枪',
    baseScore: 52,
    imageUrl: '/gear/weapon/weapon_p90.png',
    description: '使用5.7×28mm子弹的全自动无托式冲锋枪，采用了独特的顶置弹匣射击，可容纳更多弹药。',
    enabled: true,
  },
  {
    id: 'weapon_vector',
    category: 'weapon',
    subCategory: 'SMG',
    name: 'Vector冲锋枪',
    baseScore: 69,
    imageUrl: '/gear/weapon/weapon_vector.png',
    description: '.45口径的全自动冲锋枪，超高射速可以在近距离表现出强大爆发力。',
    enabled: true,
  },
  {
    id: 'weapon_uzi',
    category: 'weapon',
    subCategory: 'SMG',
    name: 'UZI冲锋枪',
    baseScore: 42,
    imageUrl: '/gear/weapon/weapon_uzi.png',
    description:
      'UZI是一款以色列制造的冲锋枪。使用9x19mm子弹，具有紧凑的尺寸和高速射击速度，广泛应用于全球多个国家的军队、警察和安全部队。',
    enabled: true,
  },
  {
    id: 'weapon_yeniu',
    category: 'weapon',
    subCategory: 'SMG',
    name: '野牛冲锋枪',
    baseScore: 42,
    imageUrl: '/gear/weapon/weapon_yeniu.png',
    description:
      'PP-19野牛是一款俄罗斯制造的冲锋枪。该冲锋枪使用9x19mm子弹，具有独特的圆筒形供弹具，主要用于警察和特种部队。',
    enabled: true,
  },
  {
    id: 'weapon_smg-45',
    category: 'weapon',
    subCategory: 'SMG',
    name: 'SMG-45冲锋枪',
    baseScore: 53,
    imageUrl: '/gear/weapon/weapon_smg-45.png',
    description: 'SMG-45发射.45口径弹药，人机工效上乘，性能稳定。',
    enabled: true,
  },
  {
    id: 'weapon_sr-3m',
    category: 'weapon',
    subCategory: 'SMG',
    name: 'SR-3M紧凑突击步枪',
    baseScore: 64,
    imageUrl: '/gear/weapon/weapon_sr-3m.png',
    description:
      'SR-3M是一款俄罗斯制造的紧凑突击步枪。该枪使用9x39mm特种子弹，具有紧凑的尺寸和强大的火力，主要用于城市战和特种作战任务。',
    enabled: true,
  },
  {
    id: 'weapon_yongshi',
    category: 'weapon',
    subCategory: 'SMG',
    name: '勇士冲锋枪',
    baseScore: 53,
    imageUrl: '/gear/weapon/weapon_yongshi.png',
    description: 'PP-19勇士基于PP-19野牛型号改进而来，使用9x19mm子弹，支持各种配件改造。',
    enabled: true,
  },
  {
    id: 'weapon_mp7',
    category: 'weapon',
    subCategory: 'SMG',
    name: 'MP7冲锋枪',
    baseScore: 69,
    imageUrl: '/gear/weapon/weapon_mp7.png',
    description: '使用4.6x30mm弹药的个人防卫武器，紧凑便携的同时拥有极强的全自动火力。',
    enabled: true,
  },
  {
    id: 'weapon_qcq171',
    category: 'weapon',
    subCategory: 'SMG',
    name: 'QCQ171冲锋枪',
    baseScore: 79,
    imageUrl: '/gear/weapon/weapon_qcq171.png',
    description: '新型冲锋枪，发射9x19mm弹药，携带方便，短小精悍，火力凶猛',
    enabled: true,
  },
  {
    id: 'weapon_mk4',
    category: 'weapon',
    subCategory: 'SMG',
    name: 'MK4冲锋枪',
    baseScore: 69,
    imageUrl: '/gear/weapon/weapon_mk4.png',
    description:
      'MK4由美国设计生产，发射4.6×30mm弹药，尺寸小巧，拥有出色的穿甲能力和机动性，能通用AR平台的众多配件，可拓展性好',
    enabled: true,
  },
  {
    id: 'weapon_qsz92g',
    category: 'weapon',
    subCategory: 'pistol',
    name: 'QSZ92G',
    baseScore: 6,
    imageUrl: '/gear/weapon/weapon_qsz92g.png',
    description: '9×19mm口径双动半自动手枪，性能均衡，改进型采用双排单进供弹。',
    enabled: true,
  },
  {
    id: 'weapon_357',
    category: 'weapon',
    subCategory: 'pistol',
    name: '.357左轮',
    baseScore: 7,
    imageUrl: '/gear/weapon/weapon_357.png',
    description: '大威力的双动左轮手枪，使用的是.357马格南口径的弹药。',
    enabled: true,
  },
  {
    id: 'weapon_desert-eagle',
    category: 'weapon',
    subCategory: 'pistol',
    name: '沙漠之鹰',
    baseScore: 15,
    imageUrl: '/gear/weapon/weapon_desert-eagle.png',
    description: '大威力的半自动手枪，使用的是短弹体.50口径的弹药。',
    enabled: true,
  },
  {
    id: 'weapon_g18',
    category: 'weapon',
    subCategory: 'pistol',
    name: 'G18',
    baseScore: 18,
    imageUrl: '/gear/weapon/weapon_g18.png',
    description: 'G系列手枪的全自动型号，以超高射速倾泻9×19mm弹药。',
    enabled: true,
  },
  {
    id: 'weapon_93r',
    category: 'weapon',
    subCategory: 'pistol',
    name: '93R',
    baseScore: 15,
    imageUrl: '/gear/weapon/weapon_93r.png',
    description: '93R手枪是一款由意大利生产的9×19mm三连发手枪，具有高爆发和可靠性。',
    enabled: true,
  },
  {
    id: 'weapon_g17',
    category: 'weapon',
    subCategory: 'pistol',
    name: 'G17',
    baseScore: 9,
    imageUrl: '/gear/weapon/weapon_g17.png',
    description: '原产国奥地利的半自动手枪，经典、可靠、耐用，采用9×19mm口径。',
    enabled: true,
  },
  {
    id: 'weapon_m1911',
    category: 'weapon',
    subCategory: 'pistol',
    name: 'M1911',
    baseScore: 12,
    imageUrl: '/gear/weapon/weapon_m1911.png',
    description:
      '发射.45 ACP口径弹药的经典半自动手枪，可靠、耐用，衍生型号众多，此型号为三角洲特种部队定制款。',
    enabled: true,
  },
  {
    id: 'weapon_compound-bow',
    category: 'weapon',
    subCategory: 'special',
    name: '复合弓',
    baseScore: 40,
    imageUrl: '/gear/weapon/weapon_compound-bow.png',
    description: '复合弓采用高强度材料，精度高且杀伤力强，可以发射多种弓箭实现不同的杀伤效果。',
    enabled: true,
  },
  {
    id: 'weapon_sv-98',
    category: 'weapon',
    subCategory: 'sniper',
    name: 'SV-98狙击步枪',
    baseScore: 40,
    imageUrl: '/gear/weapon/weapon_sv-98.png',
    description: '使用7.62x54mmR子弹的栓动式狙击步枪，子弹初速一般但具备极高的准确度。',
    enabled: true,
  },
  {
    id: 'weapon_r93',
    category: 'weapon',
    subCategory: 'sniper',
    name: 'R93狙击步枪',
    baseScore: 40,
    imageUrl: '/gear/weapon/weapon_r93.png',
    description: '直拉栓式狙击步枪，使用的是7.62×51mm口径的狙击弹药。',
    enabled: true,
  },
  {
    id: 'weapon_m700',
    category: 'weapon',
    subCategory: 'sniper',
    name: 'M700狙击步枪',
    baseScore: 44,
    imageUrl: '/gear/weapon/weapon_m700.png',
    description: '7.62×51mm口径狙击利器，可轻松狩猎目标，稳定性与射程兼具，支持现代化改装。',
    enabled: true,
  },
  {
    id: 'weapon_awm',
    category: 'weapon',
    subCategory: 'sniper',
    name: 'AWM狙击步枪',
    baseScore: 55,
    imageUrl: '/gear/weapon/weapon_awm.png',
    description:
      'AWM是一款由英国生产的狙击步枪，采用.338 Lapua Magnum弹药，具有极高的精度和射程，是军警中的顶级狙击武器。',
    enabled: true,
  },
  {
    id: 'weapon_m82',
    category: 'weapon',
    subCategory: 'sniper',
    name: 'M82狙击步枪',
    baseScore: 52,
    imageUrl: '/gear/weapon/weapon_m82.png',
    description:
      'Barrett是由美国设计生产的反器材狙击步枪，使用与重机枪相同的12.7x99mm大口径弹药，可以远距离对轻装甲单位与战斗人员造成毁灭性伤害',
    enabled: true,
  },
  {
    id: 'weapon_mini-14',
    category: 'weapon',
    subCategory: 'MP',
    name: 'Mini-14射手步枪',
    baseScore: 47,
    imageUrl: '/gear/weapon/weapon_mini-14.png',
    description: '使用5.56×45mm口径步枪弹的半自动步枪，后坐力温和，精准度可观。',
    enabled: true,
  },
  {
    id: 'weapon_vss',
    category: 'weapon',
    subCategory: 'MP',
    name: 'VSS射手步枪',
    baseScore: 52,
    imageUrl: '/gear/weapon/weapon_vss.png',
    description:
      'VSS射手步枪是一款俄罗斯制造的特种狙击步枪。该步枪使用9x39mm亚音速子弹，具有内置消音器，主要用于隐蔽和特种作战任务。',
    enabled: true,
  },
  {
    id: 'weapon_svd',
    category: 'weapon',
    subCategory: 'MP',
    name: 'SVD狙击步枪',
    baseScore: 65,
    imageUrl: '/gear/weapon/weapon_svd.png',
    description:
      'SVD是一款苏联/俄罗斯制造的半自动狙击步枪。该步枪使用7.62x54mmR子弹，具有优秀的精度和射程，是多个国家的军队和特种部队的首选狙击武器。',
    enabled: true,
  },
  {
    id: 'weapon_m14',
    category: 'weapon',
    subCategory: 'MP',
    name: 'M14射手步枪',
    baseScore: 88,
    imageUrl: '/gear/weapon/weapon_m14.png',
    description: '7.62×51mm口径的全威力步枪，切换至全自动射击模式有强大的火力，经典设计传承。',
    enabled: true,
  },
  {
    id: 'weapon_sks',
    category: 'weapon',
    subCategory: 'MP',
    name: 'SKS射手步枪',
    baseScore: 69,
    imageUrl: '/gear/weapon/weapon_sks.png',
    description: '可靠灵活的半自动步枪，使用的是7.62×39mm口径弹药，具备不错的操控性和射速。',
    enabled: true,
  },
  {
    id: 'weapon_sr-25',
    category: 'weapon',
    subCategory: 'MP',
    name: 'SR-25射手步枪',
    baseScore: 76,
    imageUrl: '/gear/weapon/weapon_sr-25.png',
    description: '采用AR系统的7.62×51mm半自动步枪，人机工效上乘，精准度不俗。',
    enabled: true,
  },
  {
    id: 'weapon_sr9',
    category: 'weapon',
    subCategory: 'MP',
    name: 'SR9射手步枪',
    baseScore: 41,
    imageUrl: '/gear/weapon/weapon_sr9.png',
    description: '民用半自动步枪，发射7.62x51mm弹药，通用部分G3改装配件',
    enabled: true,
  },
  {
    id: 'weapon_psg-1',
    category: 'weapon',
    subCategory: 'MP',
    name: 'PSG-1射手步枪',
    baseScore: 64,
    imageUrl: '/gear/weapon/weapon_psg-1.png',
    description: '使用7.62×51mm弹药的高精度的半自动狙击步枪,通用部分G3改装部件。',
    enabled: true,
  },
  {
    id: 'weapon_marlin',
    category: 'weapon',
    subCategory: 'MP',
    name: '杠杆式步枪',
    baseScore: 57,
    imageUrl: '/gear/weapon/weapon_marlin.png',
    description:
      'Marlin杠杆步枪历经150年演变，从西部拓荒时代到现代战术化改造，始终保持着技术独创性与市场适应性，在狩猎、收藏乃至战术射击领域持续焕发活力。',
    enabled: true,
  },
  {
    id: 'weapon_svch',
    category: 'weapon',
    subCategory: 'MP',
    name: 'SVCH精确射手步枪',
    baseScore: 89,
    imageUrl: '/gear/weapon/weapon_svch.png',
    description:
      'SVCH是新式武器的代表，火力强大且模块化程度高，拥有极高的改装潜力，是优秀的战场多面手',
    enabled: true,
  },
  {
    id: 'weapon_pkm',
    category: 'weapon',
    subCategory: 'LMG',
    name: 'PKM通用机枪',
    baseScore: 77,
    imageUrl: '/gear/weapon/weapon_pkm.png',
    description: '全自动机枪，采用7.62x54mmR全威力弹药，中等射速且具备强大压制力。',
    enabled: true,
  },
  {
    id: 'weapon_m249',
    category: 'weapon',
    subCategory: 'LMG',
    name: 'M249轻机枪',
    baseScore: 68,
    imageUrl: '/gear/weapon/weapon_m249.png',
    description:
      '发射5.56×45mm弹药的火力强大机枪，为战斗小组提供火力压制，确保作战优势，必要时可使用弹匣供弹。',
    enabled: true,
  },
  {
    id: 'weapon_m250',
    category: 'weapon',
    subCategory: 'LMG',
    name: 'M250通用机枪',
    baseScore: 75,
    imageUrl: '/gear/weapon/weapon_m250.png',
    description:
      '发射6.8×51mm全威力弹药的弹链供弹机枪，受弹盖经过特殊设计可保证开合后不影响瞄具归零。',
    enabled: true,
  },
  {
    id: 'weapon_qjb201',
    category: 'weapon',
    subCategory: 'LMG',
    name: 'QJB201轻机枪',
    baseScore: 69,
    imageUrl: '/gear/weapon/weapon_qjb201.png',
    description: '新型班用机枪，发射5.8x42mm弹药，双路供弹系统支持弹链或弹匣供弹',
    enabled: true,
  },
  {
    id: 'weapon_m1014',
    category: 'weapon',
    subCategory: 'shotgun',
    name: 'M1014霰弹枪',
    baseScore: 48,
    imageUrl: '/gear/weapon/weapon_m1014.png',
    description: '可靠且功能全面的12号口径半自动霰弹枪，每次发射8颗弹丸。',
    enabled: true,
  },
  {
    id: 'weapon_s12k',
    category: 'weapon',
    subCategory: 'shotgun',
    name: 'S12K霰弹枪',
    baseScore: 45,
    imageUrl: '/gear/weapon/weapon_s12k.png',
    description:
      '采用弹匣供弹的12号口径半自动霰弹枪，拥有可靠伤害和不错的弹丸扩散，连续射击时后坐力较大。',
    enabled: true,
  },
  {
    id: 'weapon_m870',
    category: 'weapon',
    subCategory: 'shotgun',
    name: 'M870霰弹枪',
    baseScore: 38,
    imageUrl: '/gear/weapon/weapon_m870.png',
    description: '经典可靠的12号口径泵动式散弹枪，每次发射8颗弹丸。',
    enabled: true,
  },
  {
    id: 'weapon_725',
    category: 'weapon',
    subCategory: 'shotgun',
    name: '725双管霰弹枪',
    baseScore: 38,
    imageUrl: '/gear/weapon/weapon_725.png',
    description:
      '725双管霰弹枪发射12号口径弹药，拥有两根上下相叠的枪管，重量轻且做工精良，有着良好的精度和可控的后坐力',
    enabled: true,
  },
  {
    id: 'weapon_fs-12',
    category: 'weapon',
    subCategory: 'shotgun',
    name: 'FS-12霰弹枪',
    baseScore: 41,
    imageUrl: '/gear/weapon/weapon_fs-12.png',
    description: 'FS-12是一款可折叠霰弹枪，易于收纳，同时支持泵动与半自动两种射击模式。',
    enabled: true,
  },
  {
    id: 'helmet_h70',
    category: 'helmet',
    subCategory: 'lv6',
    name: 'H70 精英头盔',
    baseScore: 95,
    imageUrl: '/gear/helmet/helmet_h70.png',
    description: '头部+耳部+面部',
    enabled: false,
  },
  {
    id: 'helmet_dich-9',
    category: 'helmet',
    subCategory: 'lv6',
    name: 'DICH-9重型头盔',
    baseScore: 96,
    imageUrl: '/gear/helmet/helmet_dich-9.png',
    description: '头部+耳部+下脸',
    enabled: true,
  },
  {
    id: 'helmet_gt5',
    category: 'helmet',
    subCategory: 'lv6',
    name: 'GT5 指挥官头盔',
    baseScore: 95,
    imageUrl: '/gear/helmet/helmet_gt5.png',
    description: '头部+耳部+上脸',
    enabled: true,
  },
  {
    id: 'helmet_h70-nv',
    category: 'helmet',
    subCategory: 'lv6',
    name: 'H70 夜视精英头盔',
    baseScore: 95,
    imageUrl: '/gear/helmet/helmet_h70-nv.png',
    description: '头部+耳部+面部',
    enabled: false,
  },
  {
    id: 'helmet_mask-1',
    category: 'helmet',
    subCategory: 'lv5',
    name: 'Mask-1铁壁头盔',
    baseScore: 52,
    imageUrl: '/gear/helmet/helmet_mask-1.png',
    description: '头部+耳部+面部',
    enabled: true,
  },
  {
    id: 'helmet_h09',
    category: 'helmet',
    subCategory: 'lv5',
    name: 'H09 防暴头盔',
    baseScore: 85,
    imageUrl: '/gear/helmet/helmet_h09.png',
    description: '头部+耳部+面部',
    enabled: true,
  },
  {
    id: 'helmet_dich-1',
    category: 'helmet',
    subCategory: 'lv5',
    name: 'DICH-1战术头盔',
    baseScore: 85,
    imageUrl: '/gear/helmet/helmet_dich-1.png',
    description: '头部+耳部+上脸',
    enabled: true,
  },
  {
    id: 'helmet_gn',
    category: 'helmet',
    subCategory: 'lv5',
    name: 'GN 重型头盔',
    baseScore: 85,
    imageUrl: '/gear/helmet/helmet_gn.png',
    description: '头部+耳部+面部',
    enabled: true,
  },
  {
    id: 'helmet_gn-nv',
    category: 'helmet',
    subCategory: 'lv5',
    name: 'GN 重型夜视头盔',
    baseScore: 89,
    imageUrl: '/gear/helmet/helmet_gn-nv.png',
    description: '头部+耳部+面部',
    enabled: true,
  },
  {
    id: 'helmet_gn-jz',
    category: 'helmet',
    subCategory: 'lv5',
    name: 'GN 久战重型夜视头盔',
    baseScore: 75,
    imageUrl: '/gear/helmet/helmet_gn-jz.png',
    description: '头部+耳部+面部',
    enabled: true,
  },
  {
    id: 'helmet_chixiao',
    category: 'helmet',
    subCategory: 'lv5',
    name: '赤枭装甲防弹面具',
    baseScore: 80,
    imageUrl: '/gear/helmet/helmet_chixiao.png',
    description: '仅面部',
    enabled: false,
  },
  {
    id: 'helmet_d6',
    category: 'helmet',
    subCategory: 'lv4',
    name: 'D6 战术头盔',
    baseScore: 37,
    imageUrl: '/gear/helmet/helmet_d6.png',
    description: '头部+耳部+面部',
    enabled: true,
  },
  {
    id: 'helmet_mhs',
    category: 'helmet',
    subCategory: 'lv4',
    name: 'MHS 战术头盔',
    baseScore: 60,
    imageUrl: '/gear/helmet/helmet_mhs.png',
    description: '头部+耳部',
    enabled: true,
  },
  {
    id: 'helmet_dich-2',
    category: 'helmet',
    subCategory: 'lv4',
    name: 'DICH 训练头盔',
    baseScore: 79,
    imageUrl: '/gear/helmet/helmet_dich-2.png',
    description: '头部+耳部',
    enabled: true,
  },
  {
    id: 'helmet_gt1',
    category: 'helmet',
    subCategory: 'lv4',
    name: 'GT1 战术头盔',
    baseScore: 70,
    imageUrl: '/gear/helmet/helmet_gt1.png',
    description: '头部+耳部+上脸',
    enabled: true,
  },
  {
    id: 'helmet_fby',
    category: 'helmet',
    subCategory: 'lv3',
    name: '防暴头盔',
    baseScore: 32,
    imageUrl: '/gear/helmet/helmet_fby.png',
    description: '头部+耳部',
    enabled: true,
  },
  {
    id: 'helmet_h07',
    category: 'helmet',
    subCategory: 'lv3',
    name: 'H07 战术头盔',
    baseScore: 40,
    imageUrl: '/gear/helmet/helmet_h07.png',
    description: '头部',
    enabled: true,
  },
  {
    id: 'helmet_das',
    category: 'helmet',
    subCategory: 'lv3',
    name: 'DAS 防弹头盔',
    baseScore: 45,
    imageUrl: '/gear/helmet/helmet_das.png',
    description: '头部',
    enabled: true,
  },
  {
    id: 'helmet_mc201',
    category: 'helmet',
    subCategory: 'lv3',
    name: 'MC201 头盔',
    baseScore: 50,
    imageUrl: '/gear/helmet/helmet_mc201.png',
    description: '头部+耳部',
    enabled: true,
  },
  {
    id: 'helmet_fmh',
    category: 'helmet',
    subCategory: 'lv2',
    name: '复古摩托头盔',
    baseScore: 15,
    imageUrl: '/gear/helmet/helmet_fmh.png',
    description: '头部',
    enabled: true,
  },
  {
    id: 'helmet_h01',
    category: 'helmet',
    subCategory: 'lv2',
    name: 'H01 战术头盔',
    baseScore: 20,
    imageUrl: '/gear/helmet/helmet_h01.png',
    description: '头部',
    enabled: true,
  },
  {
    id: 'helmet_dro',
    category: 'helmet',
    subCategory: 'lv2',
    name: 'DRO 战术头盔',
    baseScore: 22,
    imageUrl: '/gear/helmet/helmet_dro.png',
    description: '头部',
    enabled: true,
  },
  {
    id: 'helmet_mc',
    category: 'helmet',
    subCategory: 'lv2',
    name: 'MC防弹头盔',
    baseScore: 27,
    imageUrl: '/gear/helmet/helmet_mc.png',
    description: '头部',
    enabled: true,
  },
  {
    id: 'helmet_old',
    category: 'helmet',
    subCategory: 'lv1',
    name: '老式钢盔',
    baseScore: 5,
    imageUrl: '/gear/helmet/helmet_old.png',
    description: '头部',
    enabled: true,
  },
  {
    id: 'helmet_anbao',
    category: 'helmet',
    subCategory: 'lv1',
    name: '安保头盔',
    baseScore: 8,
    imageUrl: '/gear/helmet/helmet_anbao.png',
    description: '头部',
    enabled: true,
  },
  {
    id: 'helmet_bini',
    category: 'helmet',
    subCategory: 'lv1',
    name: '奔尼帽',
    baseScore: 7,
    imageUrl: '/gear/helmet/helmet_bini.png',
    description: '头部',
    enabled: true,
  },
  {
    id: 'helmet_outdoor',
    category: 'helmet',
    subCategory: 'lv1',
    name: '户外棒球帽',
    baseScore: 10,
    imageUrl: '/gear/helmet/helmet_outdoor.png',
    description: '头部',
    enabled: true,
  },
  {
    id: 'armor_jingang',
    category: 'armor',
    subCategory: 'lv6',
    name: '金刚防弹衣',
    baseScore: 94,
    imageUrl: '/gear/armor/armor_jingang.png',
    description:
      '阿萨拉部队最强的护甲，符合6级防弹标准，也会严重影响穿戴者的移动速度和武器操控性。',
    enabled: true,
  },
  {
    id: 'armor_ha-2',
    category: 'armor',
    subCategory: 'lv6',
    name: 'HA-2防弹装甲',
    baseScore: 95,
    imageUrl: '/gear/armor/armor_ha-2.png',
    description:
      '基于Hvk-2重型防弹衣的迭代版本，符合6级防弹标准，会严重影响穿戴者的移动速度和武器操控性。',
    enabled: false,
  },
  {
    id: 'armor_tricek-mas2',
    category: 'armor',
    subCategory: 'lv6',
    name: '特里克MAS2.0装甲',
    baseScore: 96,
    imageUrl: '/gear/armor/armor_tricek-mas2.png',
    description:
      '三角洲小队基于上身全防护需求研发的特里克战术模块化护甲系统，MAS2.0型拥有强大的防护能力，符合6级防弹标准，但同样会影响穿戴者的移动速度和武器操控性。',
    enabled: true,
  },
  {
    id: 'armor_titan',
    category: 'armor',
    subCategory: 'lv6',
    name: '泰坦防弹装甲',
    baseScore: 95,
    imageUrl: '/gear/armor/armor_titan.png',
    description:
      'GTI研发部门基于大面积、全包围的设计目标研发的高性能通用装甲系列防弹衣，拥有多种模块化选配装具，符合6级防弹标准，但同样会影响穿戴者的移动速度和武器操控性。',
    enabled: true,
  },
  {
    id: 'armor_jingying',
    category: 'armor',
    subCategory: 'lv5',
    name: '精英防弹背心',
    baseScore: 85,
    imageUrl: '/gear/armor/armor_jingying.png',
    description:
      '阿萨拉部队为精英人员配置的最顶级装甲，符合5级防弹标准，会少量影响穿戴者的移动速度和武器操控性。',
    enabled: true,
  },
  {
    id: 'armor_hvk-2',
    category: 'armor',
    subCategory: 'lv5',
    name: 'Hvk-2防弹衣',
    baseScore: 77,
    imageUrl: '/gear/armor/armor_hvk-2.png',
    description:
      '作为哈夫克公司最高级防护标准的第一代作品，符合5级防弹标准，但同时带来惊人的重量和严重的移动速度和武器操控性衰减。',
    enabled: true,
  },
  {
    id: 'armor_fs',
    category: 'armor',
    subCategory: 'lv5',
    name: 'FS复合防弹衣',
    baseScore: 86,
    imageUrl: '/gear/armor/armor_fs.png',
    description:
      '符合5级防弹标准，通过模块化设计降低了一部分重量，但高级防弹插板的重量仍会明显降低穿戴者的移动速度和武器操控性。',
    enabled: true,
  },
  {
    id: 'armor_heavy',
    category: 'armor',
    subCategory: 'lv5',
    name: '重型突击背心',
    baseScore: 87,
    imageUrl: '/gear/armor/armor_heavy.png',
    description:
      'GTI研发部门对全包围防护装甲的初代实验产品，符合5级防弹标准，同时会严重影响穿戴者的移动速度和武器操控性。',
    enabled: true,
  },
  {
    id: 'armor_chixiao',
    category: 'armor',
    subCategory: 'lv5',
    name: '赤枭重装突击背心',
    baseScore: 80,
    imageUrl: '/gear/armor/armor_chixiao.png',
    description:
      '阿萨拉部队为特种作战设计的作战背心，只分配给最顶尖的作战人员，符合5级防弹标准，贴合的设计保证了穿戴者在长距离奔袭下保持轻便，但会有较大的武器操控性惩罚。',
    enabled: false,
  },
  {
    id: 'armor_wushi',
    category: 'armor',
    subCategory: 'lv4',
    name: '武士防弹背心',
    baseScore: 60,
    imageUrl: '/gear/armor/armor_wushi.png',
    description: '稍显风格化的防弹装甲，看上去是阿萨拉部队喜欢的样子，符合4级防弹标准。',
    enabled: true,
  },
  {
    id: 'armor_tuji',
    category: 'armor',
    subCategory: 'lv4',
    name: '突击手防弹背心',
    baseScore: 60,
    imageUrl: '/gear/armor/armor_tuji.png',
    description:
      '搭载哈夫克公司全新防弹工艺的防弹衣，符合4级防弹标准，会大幅影响穿戴者的移动速度，同时轻微影响穿戴者的武器操控性。',
    enabled: true,
  },
  {
    id: 'armor_dt-avs',
    category: 'armor',
    subCategory: 'lv4',
    name: 'DT-AVS防弹衣',
    baseScore: 65,
    imageUrl: '/gear/armor/armor_dt-avs.png',
    description:
      '三角洲小队配装的新款防弹衣，保持了腹部防护设计，符合4级防弹标准，但较重的重量会明显影响穿戴者的移动速度和武器操控性。',
    enabled: true,
  },
  {
    id: 'armor_mk-2',
    category: 'armor',
    subCategory: 'lv4',
    name: 'MK-2战术背心',
    baseScore: 70,
    imageUrl: '/gear/armor/armor_mk-2.png',
    description:
      'GTI研发部门全新设计的防弹衣，符合4级防弹标准，但增加的重量会严重影响穿戴者的移动速度和武器操控性。',
    enabled: true,
  },
  {
    id: 'armor_hmp',
    category: 'armor',
    subCategory: 'lv4',
    name: 'HMP特勤防弹衣',
    baseScore: 62,
    imageUrl: '/gear/armor/armor_hmp.png',
    description: '搭载哈夫克安保部门使用新型材质技术的防弹衣，符合4级防弹标准。',
    enabled: true,
  },
  {
    id: 'armor_zhishi',
    category: 'armor',
    subCategory: 'lv3',
    name: '制式防弹背心',
    baseScore: 40,
    imageUrl: '/gear/armor/armor_zhishi.png',
    description: '阿萨拉高级士兵才能选择的高品质防弹衣，符合3级防弹标准。',
    enabled: true,
  },
  {
    id: 'armor_kuaichai',
    category: 'armor',
    subCategory: 'lv3',
    name: 'Hvk快拆防弹衣',
    baseScore: 40,
    imageUrl: '/gear/armor/armor_kuaichai.png',
    description:
      '前后双防弹插板设计的哈夫克标准装备，符合3级防弹标准，会明显影响穿戴者的移动速度和武器操控性。',
    enabled: true,
  },
  {
    id: 'armor_tg-h',
    category: 'armor',
    subCategory: 'lv3',
    name: 'TG-H防弹衣',
    baseScore: 43,
    imageUrl: '/gear/armor/armor_tg-h.png',
    description:
      '符合3级防弹标准，同时加挂了腹部防护，增加对腹部的防护覆盖，增加的重量会明显影响穿戴者的移动速度和武器操控性。',
    enabled: true,
  },
  {
    id: 'armor_sheshou',
    category: 'armor',
    subCategory: 'lv3',
    name: '射手战术背心',
    baseScore: 45,
    imageUrl: '/gear/armor/armor_sheshou.png',
    description:
      '符合3级防弹标准，同时加装腹部防护，增加对腹部的防护覆盖，增加的重量会大幅影响穿戴者的移动速度和武器操控性。',
    enabled: true,
  },
  {
    id: 'armor_jianyi',
    category: 'armor',
    subCategory: 'lv2',
    name: '简易防刺服',
    baseScore: 18,
    imageUrl: '/gear/armor/armor_jianyi.png',
    description: '阿萨拉士兵大规模列装的标准装备，能阻挡1级子弹穿透。',
    enabled: true,
  },
  {
    id: 'armor_ht',
    category: 'armor',
    subCategory: 'lv2',
    name: 'HT战术背心',
    baseScore: 20,
    imageUrl: '/gear/armor/armor_ht.png',
    description: '符合2级防弹标准的哈夫克标准装备。',
    enabled: true,
  },
  {
    id: 'armor_tg',
    category: 'armor',
    subCategory: 'lv2',
    name: 'TG战术防弹衣',
    baseScore: 22,
    imageUrl: '/gear/armor/armor_tg.png',
    description:
      '三角洲小队基于灵活作战与提升穿戴舒适性需求研发的通用战术防弹背心，高拓展性使其能挂载多种战术装具，符合2级防弹标准。',
    enabled: true,
  },
  {
    id: 'armor_tongyong',
    category: 'armor',
    subCategory: 'lv2',
    name: '通用战术背心',
    baseScore: 25,
    imageUrl: '/gear/armor/armor_tongyong.png',
    description:
      'GTI研发部门设计的通用装甲系列作战背心之一，快拆设计能够让穿戴者在狭小空间实现内快速反应，符合2级防弹标准的GTI标准装备。',
    enabled: true,
  },
  {
    id: 'armor_motoma',
    category: 'armor',
    subCategory: 'lv1',
    name: '摩托马甲',
    baseScore: 7,
    imageUrl: '/gear/armor/armor_motoma.png',
    description: '轻薄舒适，但对子弹几乎没有防护能力。',
    enabled: true,
  },
  {
    id: 'armor_anbao',
    category: 'armor',
    subCategory: 'lv1',
    name: '安保防弹衣',
    baseScore: 6,
    imageUrl: '/gear/armor/armor_anbao.png',
    description: '使用复合材质，哈夫克士兵最喜欢的轻便之选。',
    enabled: true,
  },
  {
    id: 'armor_nilon',
    category: 'armor',
    subCategory: 'lv1',
    name: '尼龙防弹衣',
    baseScore: 5,
    imageUrl: '/gear/armor/armor_nilon.png',
    description: '上世纪列装给三角洲小队新兵的软式防弹衣，轻便透气，但防护能力实在薄弱。',
    enabled: true,
  },
  {
    id: 'armor_light',
    category: 'armor',
    subCategory: 'lv1',
    name: '轻型防弹衣',
    baseScore: 4,
    imageUrl: '/gear/armor/armor_light.png',
    description: 'GTI新兵训练时佩戴的防护装备。',
    enabled: true,
  },
  {
    id: 'operator_weilong',
    category: 'operator',
    subCategory: 'assault',
    name: '威龙',
    baseScore: 50,
    description: '王宇昊',
    imageUrl: '/gear/operator/operator_weilong.png',
    enabled: true,
  },
  {
    id: 'operator_wuming',
    category: 'operator',
    subCategory: 'assault',
    name: '无名',
    baseScore: 50,
    description: '埃利·德·孟贝尔',
    imageUrl: '/gear/operator/operator_wuming.png',
    enabled: true,
  },
  {
    id: 'operator_jifeng',
    category: 'operator',
    subCategory: 'assault',
    name: '疾风',
    baseScore: 50,
    description: '克莱尔·安·拜尔斯',
    imageUrl: '/gear/operator/operator_jifeng.png',
    enabled: true,
  },
  {
    id: 'operator_honglang',
    category: 'operator',
    subCategory: 'assault',
    name: '红狼',
    baseScore: 50,
    description: '凯·席尔瓦',
    imageUrl: '/gear/operator/operator_honglang.png',
    enabled: true,
  },
  {
    id: 'operator_huixiang',
    category: 'operator',
    subCategory: 'recon',
    name: '回响',
    baseScore: 50,
    description: '卢克·埃弗利',
    imageUrl: '/gear/operator/operator_huixiang.png',
    enabled: true,
  },
  {
    id: 'operator_yinyi',
    category: 'operator',
    subCategory: 'recon',
    name: '银翼',
    baseScore: 50,
    description: '兰登·哈里森',
    imageUrl: '/gear/operator/operator_yinyi.png',
    enabled: true,
  },
  {
    id: 'operator_luna',
    category: 'operator',
    subCategory: 'recon',
    name: '露娜',
    baseScore: 50,
    description: '金卢娜',
    imageUrl: '/gear/operator/operator_luna.png',
    enabled: true,
  },
  {
    id: 'operator_haizhua',
    category: 'operator',
    subCategory: 'recon',
    name: '骇爪',
    baseScore: 50,
    description: '麦晓雯',
    imageUrl: '/gear/operator/operator_haizhua.png',
    enabled: true,
  },
  {
    id: 'operator_gu',
    category: 'operator',
    subCategory: 'support',
    name: '蛊',
    baseScore: 50,
    description: '佐娅·庞琴科娃',
    imageUrl: '/gear/operator/operator_gu.png',
    enabled: true,
  },
  {
    id: 'operator_fengyi',
    category: 'operator',
    subCategory: 'support',
    name: '蜂医',
    baseScore: 50,
    description: '罗伊·斯米',
    imageUrl: '/gear/operator/operator_fengyi.png',
    enabled: true,
  },
  {
    id: 'operator_die',
    category: 'operator',
    subCategory: 'support',
    name: '蝶',
    baseScore: 50,
    description: '莉娜·范德梅尔',
    imageUrl: '/gear/operator/operator_die.png',
    enabled: true,
  },
  {
    id: 'operator_wululu',
    category: 'operator',
    subCategory: 'engineer',
    name: '乌鲁鲁',
    baseScore: 50,
    description: '大卫·费莱尔',
    imageUrl: '/gear/operator/operator_wululu.png',
    enabled: true,
  },
  {
    id: 'operator_bite',
    category: 'operator',
    subCategory: 'engineer',
    name: '比特',
    baseScore: 50,
    description: '拉希德·拉哈尔',
    imageUrl: '/gear/operator/operator_bite.png',
    enabled: true,
  },
  {
    id: 'operator_yedan',
    category: 'operator',
    subCategory: 'engineer',
    name: '液氮',
    baseScore: 50,
    description: '加布里埃尔·默里尔',
    imageUrl: '/gear/operator/operator_yedan.png',
    enabled: true,
  },
  {
    id: 'operator_shenlan',
    category: 'operator',
    subCategory: 'engineer',
    name: '深蓝',
    baseScore: 50,
    description: '阿列克谢.彼得罗夫',
    imageUrl: '/gear/operator/operator_shenlan.png',
    enabled: true,
  },
  {
    id: 'operator_muyangren',
    category: 'operator',
    subCategory: 'engineer',
    name: '牧羊人',
    baseScore: 50,
    description: '泰瑞·缪萨',
    imageUrl: '/gear/operator/operator_muyangren.png',
    enabled: true,
  },
];
